### ISSUE TITLE
生成中文训练库出错

### ISSUE THREAD

**Issue by kernel8liang** [wanghaisheng/awesome-ocr#36]
参照wiki "中文训练库的构建", 使用字库　“思源黑体: 简体中文 ttf 版本”。
 
```
ocropus-linegen -t tests/test-chinese -f KaiGenGothicSC-Regular.ttf
```
出错

```
Traceback (most recent call last):
  File "/home/liang/anaconda2/bin/ocropus-linegen", line 213, in <module>
    size=size,sigma=sigma,threshold=threshold)
  File "/home/liang/anaconda2/bin/ocropus-linegen", line 169, in genline
    last_font = ImageFont.truetype(fontfile,size)
  File "/home/liang/anaconda2/lib/python2.7/site-packages/PIL/ImageFont.py", line 238, in truetype
    return FreeTypeFont(font, size, index, encoding)
  File "/home/liang/anaconda2/lib/python2.7/site-packages/PIL/ImageFont.py", line 127, in __init__
    self.font = core.getfont(font, size, index, encoding)
IOError: broken table
```

**Comment by kernel8liang** [comment]
换了一个字体，ＯＫ了。
