### ISSUE TITLE
Digit Segmentation and Recognition using OpenCV and MLP test

### ISSUE THREAD

**Issue by wanghaisheng** [wanghaisheng/awesome-ocr#58]
Digit Segmentation and Recognition using OpenCV and MLP
https://github.com/kyper999/OCR

```

(py2.7) ➜  scripts git:(master) pip install --upgrade https://github.com/Lasagne/Lasagne/archive/master.zip
(py2.7) ➜  scripts git:(master) pip install --upgrade https://github.com/Theano/Theano/archive/rel-0.8.2.zip      
(py2.7) ➜  scripts git:(master) python main.py

**Comment by wanghaisheng** [comment]
```
(py2.7) ➜  scripts git:(master) ✗ python cvTest2.py
 
===================================================
    Digit Classification Using MLP and OpenCV 
===================================================

Summary:
        Digit Segmentation and Classification Using 
        MLP and OpenCV on GoogleStreetView Data Base

        Created by:  Chenxing Ouyang & Jiali Xie


Preprocessing Image, Cropping Digits Into 28 X 28 Image Matrices

Image Preprocessing Done, 30 Potential Digits Were Cropped Out

Building Multilayer Perceptron Network From Trained Model

Predicting Results

Image    Digit     probability
0.png      8         0.873423
1.png      8         0.873423
2.png      8         0.951135
3.png      8         0.951135
4.png      8         0.950026
5.png      8         0.912070
6.png      8         0.781447
7.png      8         0.912070
8.png      8         0.919832
9.png      1         0.945095
10.png      5         0.659422
11.png      5         0.656820
12.png      3         0.971028
13.png      8         0.919832
14.png      1         0.945095
15.png      5         0.659422
16.png      5         0.656820
17.png      3         0.971028
18.png      1         0.999937
19.png      1         0.999937
20.png      6         0.999998
21.png      6         0.999999
22.png      3         0.999555
23.png      2         0.999934
24.png      1         0.994189
25.png      2         0.764601
26.png      3         0.999555
27.png      2         0.999934
28.png      1         0.994189
29.png      2         0.764601
OpenCV Error: Assertion failed (dsize.area() || (inv_scale_x > 0 && inv_scale_y > 0)) in resize, file /Users/jenkins/miniconda/0/2.7/conda-bld/work/opencv-2.4.11/modules/imgproc/src/imgwarp.cpp, line 1969
Traceback (most recent call last):
  File "cvTest2.py", line 62, in <module>
    cropped_img = ocr.save_digit_to_binary_img_as_mnist("../../IMG_20170922_142015.jpg", 5)
  File "/Users/wanghaisheng/workspace/OCR/binarization-experiments/Digit-Segmentation-and-Recognition-using-OpenCV-and-MLP/scripts/ocr.py", line 62, in save_digit_to_binary_img_as_mnist
    resized_img = resize(thresh, dim)
  File "/Users/wanghaisheng/workspace/OCR/binarization-experiments/Digit-Segmentation-and-Recognition-using-OpenCV-and-MLP/scripts/ocr.py", line 135, in resize
    resized_img = cv2.resize(img, dim, interpolation = cv2.INTER_AREA)
cv2.error: /Users/jenkins/miniconda/0/2.7/conda-bld/work/opencv-2.4.11/modules/imgproc/src/imgwarp.cpp:1969: error: (-215) dsize.area() || (inv_scale_x > 0 && inv_scale_y > 0) in function resize


```
