### ISSUE TITLE
ctpn 测试

### ISSUE THREAD

**Issue by wanghaisheng** [wanghaisheng/awesome-ocr#62]
```
docker run  --rm -it  -v `pwd`:/opt/ctpn/CTPN/demo_images -p 8888:8888  dc/ctpn 

docker run  --rm -it  -v `pwd`:/opt/ctpn/CTPN/demo_images  dc/ctpn /bin/bash
root@8a1d73be4cbc:/opt/ctpn/CTPN# python tools/demo.py --no-gpu 
```

**Comment by wanghaisheng** [comment]
```
➜  CTPN git:(master) ✗ docker run  --rm -it dc/ctpn bin/bash
docker: Error response from daemon: oci runtime error: container_linux.go:265: starting container process caused "exec: \"bin/bash\": stat bin/bash: no such file or directory".
➜  CTPN git:(master) ✗ docker run  --rm -it dc/ctpn /bin/bash
root@8a1d73be4cbc:/opt/ctpn/CTPN# ll
total 52
drwxr-xr-x 17 root root 4096 Sep 23 20:09 ./
drwxr-xr-x 11 root root 4096 Sep 23 20:09 ../
drwxr-xr-x  8 root root 4096 Sep 23 19:27 .git/
-rw-r--r--  1 root root   45 Sep 23 12:56 .gitignore
-rw-r--r--  1 root root 2843 Sep 23 12:56 Dockerfile
-rw-r--r--  1 root root 1207 Sep 23 12:56 LICENSE
-rw-r--r--  1 root root  203 Sep 23 12:56 Makefile
-rw-r--r--  1 root root 2553 Sep 23 12:56 README.md
drwxr-xr-x 17 root root 4096 Sep 23 19:27 caffe/
drwxr-xr-x  2 root root 4096 Sep 23 12:56 demo_images/
drwxr-xr-x  2 root root 4096 Sep 23 13:30 models/
drwxr-xr-x  5 root root 4096 Sep 23 20:09 src/
drwxr-xr-x  2 root root 4096 Sep 23 12:56 tools/
root@8a1d73be4cbc:/opt/ctpn/CTPN# python tools/
cfg.py   demo.py  
root@8a1d73be4cbc:/opt/ctpn/CTPN# python tools/demo.py 
libdc1394 error: Failed to initialize libdc1394
Traceback (most recent call last):
  File "tools/demo.py", line 22, in <module>
    from other import draw_boxes, resize_im, CaffeModel
  File "./src/other.py", line 1, in <module>
    import cv2, caffe
  File "./caffe/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver
  File "./caffe/python/caffe/pycaffe.py", line 14, in <module>
    import caffe.io
  File "./caffe/python/caffe/io.py", line 2, in <module>
    import skimage.io
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/__init__.py", line 7, in <module>
    from .manage_plugins import *
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/manage_plugins.py", line 28, in <module>
    from .collection import imread_collection_wrapper
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/collection.py", line 14, in <module>
    from ..external.tifffile import TiffFile
  File "/usr/local/lib/python2.7/dist-packages/skimage/external/tifffile/__init__.py", line 1, in <module>
    from .tifffile import imsave, imread, imshow, TiffFile, TiffWriter, TiffSequence
  File "/usr/local/lib/python2.7/dist-packages/skimage/external/tifffile/tifffile.py", line 293, in <module>
    from . import _tifffile
RuntimeError: module compiled against API version 0xa but this version of numpy is 0x9
Segmentation fault
root@8a1d73be4cbc:/opt/ctpn/CTPN# sudo ln /dev/null /dev/raw1394   
root@8a1d73be4cbc:/opt/ctpn/CTPN# python tools/demo.py 
Traceback (most recent call last):
  File "tools/demo.py", line 22, in <module>
    from other import draw_boxes, resize_im, CaffeModel
  File "./src/other.py", line 1, in <module>
    import cv2, caffe
  File "./caffe/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver
  File "./caffe/python/caffe/pycaffe.py", line 14, in <module>
    import caffe.io
  File "./caffe/python/caffe/io.py", line 2, in <module>
    import skimage.io
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/__init__.py", line 7, in <module>
    from .manage_plugins import *
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/manage_plugins.py", line 28, in <module>
    from .collection import imread_collection_wrapper
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/collection.py", line 14, in <module>
    from ..external.tifffile import TiffFile
  File "/usr/local/lib/python2.7/dist-packages/skimage/external/tifffile/__init__.py", line 1, in <module>
    from .tifffile import imsave, imread, imshow, TiffFile, TiffWriter, TiffSequence
  File "/usr/local/lib/python2.7/dist-packages/skimage/external/tifffile/tifffile.py", line 293, in <module>
    from . import _tifffile
RuntimeError: module compiled against API version 0xa but this version of numpy is 0x9
Segmentation fault
root@8a1d73be4cbc:/opt/ctpn/CTPN# pip install numpy --upgrade
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Collecting numpy
  Downloading numpy-1.13.1-cp27-cp27mu-manylinux1_x86_64.whl (16.6MB)
    100% |################################| 16.6MB 73kB/s 
Installing collected packages: numpy
  Found existing installation: numpy 1.8.2
    DEPRECATION: Uninstalling a distutils installed project (numpy) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling numpy-1.8.2:
      Successfully uninstalled numpy-1.8.2
Successfully installed numpy-1.13.1
root@8a1d73be4cbc:/opt/ctpn/CTPN# python tools/demo.py 
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0923 20:13:40.654605    29 common.cpp:103] Cannot create Cublas handle. Cublas won't be available.
E0923 20:13:40.657570    29 common.cpp:110] Cannot create Curand generator. Curand won't be available.
F0923 20:13:40.660428    29 common.cpp:141] Check failed: error == cudaSuccess (30 vs. 0)  unknown error
*** Check failure stack trace: ***
Aborted
root@8a1d73be4cbc:/opt/ctpn/CTPN# python tools/demo.py --no-gpu 
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0923 20:14:08.279448    37 common.cpp:103] Cannot create Cublas handle. Cublas won't be available.
E0923 20:14:08.282176    37 common.cpp:110] Cannot create Curand generator. Curand won't be available.
I0923 20:14:08.287258    37 net.cpp:50] Initializing net from parameters: 
name: "VGG_ILSVRC_16_layers"
input: "data"

```

**Comment by wanghaisheng** [comment]
Docker file 
```
FROM nvidia/cuda:7.0-runtime-ubuntu14.04
MAINTAINER Varun Suresh <fab.varun@gmail.com>

RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        cmake \
        git \
        wget \
        zip \
        unzip \
        libatlas-base-dev \
        libboost-all-dev \
        libgflags-dev \
        libgoogle-glog-dev \
        libhdf5-serial-dev \
        libleveldb-dev \
        liblmdb-dev \
        libopencv-dev \
        libprotobuf-dev \
        libsnappy-dev \
        protobuf-compiler \
        python-dev \
        python-numpy \
        python-pip \
        python-setuptools \
        python-scipy && \
    rm -rf /var/lib/apt/lists/*

ENV CTPN_ROOT=/opt/ctpn
WORKDIR $CTPN_ROOT

RUN git clone --depth 1 https://github.com/tianzhi0549/CTPN.git
WORKDIR $CTPN_ROOT/CTPN/caffe



ADD ctpn_trained_model.caffemodel  $CTPN_ROOT/CTPN/models



# Missing "packaging" package
RUN pip install -i https://pypi.tuna.tsinghua.edu.cn/simple  --upgrade pip
RUN pip install -i https://pypi.tuna.tsinghua.edu.cn/simple  packaging

RUN cd python && for req in $(cat requirements.txt) pydot; do pip install -i https://pypi.tuna.tsinghua.edu.cn/simple  $req; done && cd ..
RUN git clone https://github.com/NVIDIA/nccl.git
RUN apt-get update && apt-get install -y --no-install-recommends \
    cuda=7.0-28
WORKDIR /

# Download the CUDA drivers from https://developer.nvidia.com/rdp/cudnn-archive and place it here  :
ADD cudnn-7.0-linux-x64-v4.0-prod.tgz /

WORKDIR /cuda
RUN cp -P include/cudnn.h /usr/include
RUN cp -P lib64/libcudnn* /usr/lib/x86_64-linux-gnu/

WORKDIR $CTPN_ROOT/CTPN/caffe

ADD ./caffe/Makefile.config $CTPN_ROOT/CTPN/caffe
RUN cat Makefile.config
#RUN cp Makefile.config.example Makefile.config
RUN apt-get update && apt-get install -y --no-install-recommends \
    vim
#RUN cd nccl && make -j install && 
#RUN    cd .. && rm -rf nccl && \
RUN   cd $CTPN_ROOT/CTPN/caffe  &&   \
   mkdir build && cd build && \
     cmake -DUSE_CUDNN=0 .. && \
#     WITH_PYTHON_LAYER=1 && \
     pwd && \
     make -j"$(nproc)" && make pycaffe

# Set the environment variables so that the paths are correctly configured
ENV PYCAFFE_ROOT $CTPN_ROOT/CTPN/caffe/python
ENV PYTHONPATH $PYCAFFE_ROOT:$PYTHONPATH
ENV PATH $CTPN_ROOT/CTPN/caffe/build/tools:$PYCAFFE_ROOT:$PATH
RUN echo "$CTPN_ROOT/CTPN/caffe/build/lib" >> /etc/ld.so.conf.d/caffe.conf && ldconfig

# To make sure the python layer builds - Need to figure out a cleaner way to do this.
RUN cp $CTPN_ROOT/CTPN/src/layers/* $CTPN_ROOT/CTPN/caffe/src/caffe/layers/
RUN cp $CTPN_ROOT/CTPN/src/*.py $CTPN_ROOT/CTPN/caffe/src/caffe/
RUN cp -r $CTPN_ROOT/CTPN/src/utils $CTPN_ROOT/CTPN/caffe/src/caffe/

# Install Opencv - 2.4.12 :

RUN cd ~ && \
    mkdir -p ocv-tmp && \
    cd ocv-tmp && \
    wget https://github.com/Itseez/opencv/archive/2.4.12.zip  && \
    unzip 2.4.12.zip && \
    cd opencv-2.4.12 && \
    mkdir release && \
    cd release && \
    cmake -D CMAKE_BUILD_TYPE=RELEASE \
          -D CMAKE_INSTALL_PREFIX=/usr/local \
          -D BUILD_PYTHON_SUPPORT=ON \
          .. && \
    make -j8 && \
    make install && \
    rm -rf ~/ocv-tmp

WORKDIR $CTPN_ROOT/CTPN
RUN make

```

**Comment by wanghaisheng** [comment]
Makefile.config
```
## Refer to http://caffe.berkeleyvision.org/installation.html
# Contributions simplifying and improving our build system are welcome!

# cuDNN acceleration switch (uncomment to build with cuDNN).
# USE_CUDNN := 1

# CPU-only switch (uncomment to build without GPU support).
CPU_ONLY := 1

# To customize your choice of compiler, uncomment and set the following.
# N.B. the default for Linux is g++ and the default for OSX is clang++
# CUSTOM_CXX := g++

# CUDA directory contains bin/ and lib/ directories that we need.
CUDA_DIR := /usr/local/cuda
# On Ubuntu 14.04, if cuda tools are installed via
# "sudo apt-get install nvidia-cuda-toolkit" then use this instead:
# CUDA_DIR := /usr

# CUDA architecture setting: going with all of them.
# For CUDA < 6.0, comment the *_50 lines for compatibility.
CUDA_ARCH := -gencode arch=compute_20,code=sm_20 \
		-gencode arch=compute_20,code=sm_21 \
		-gencode arch=compute_30,code=sm_30 \
		-gencode arch=compute_35,code=sm_35 \
		-gencode arch=compute_50,code=sm_50 
#		\
#		-gencode arch=compute_50,code=compute_50

# BLAS choice:
# atlas for ATLAS (default)
# mkl for MKL
# open for OpenBlas
BLAS := atlas
# Custom (MKL/ATLAS/OpenBLAS) include and lib directories.
# Leave commented to accept the defaults for your choice of BLAS
# (which should work)!
# BLAS_INCLUDE := /path/to/your/blas
# BLAS_LIB := /path/to/your/blas

# Homebrew puts openblas in a directory that is not on the standard search path
# BLAS_INCLUDE := $(shell brew --prefix openblas)/include
# BLAS_LIB := $(shell brew --prefix openblas)/lib

# This is required only if you will compile the matlab interface.
# MATLAB directory should contain the mex binary in /bin.
# MATLAB_DIR := /usr/local
# MATLAB_DIR := /Applications/MATLAB_R2012b.app

# NOTE: this is required only if you will compile the python interface.
# We need to be able to find Python.h and numpy/arrayobject.h.
#PYTHON_INCLUDE := /usr/include/python2.7 \
#		/usr/lib/python2.7/dist-packages/numpy/core/include
# Anaconda Python distribution is quite popular. Include path:
# Verify anaconda location, sometimes it's in root.
 ANACONDA_HOME := $(HOME)/anaconda
 PYTHON_INCLUDE := $(ANACONDA_HOME)/include \
		# $(ANACONDA_HOME)/include/python2.7 \
		# $(ANACONDA_HOME)/lib/python2.7/site-packages/numpy/core/include \

# We need to be able to find libpythonX.X.so or .dylib.
#PYTHON_LIB := /usr/lib
 PYTHON_LIB := $(ANACONDA_HOME)/lib

# Homebrew installs numpy in a non standard path (keg only)
# PYTHON_INCLUDE += $(dir $(shell python -c 'import numpy.core; print(numpy.core.__file__)'))/include
# PYTHON_LIB += $(shell brew --prefix numpy)/lib

# Uncomment to support layers written in Python (will link against Python libs)
 WITH_PYTHON_LAYER := 1

# Whatever else you find you need goes here.
INCLUDE_DIRS := $(PYTHON_INCLUDE) /usr/local/include
LIBRARY_DIRS := $(PYTHON_LIB) /usr/local/lib /usr/lib

# If Homebrew is installed at a non standard location (for example your home directory) and you use it for general dependencies
# INCLUDE_DIRS += $(shell brew --prefix)/include
# LIBRARY_DIRS += $(shell brew --prefix)/lib

# Uncomment to use `pkg-config` to specify OpenCV library paths.
# (Usually not necessary -- OpenCV libraries are normally installed in one of the above $LIBRARY_DIRS.)
# USE_PKG_CONFIG := 1

BUILD_DIR := build
DISTRIBUTE_DIR := distribute

# Uncomment for debugging. Does not work on OSX due to https://github.com/BVLC/caffe/issues/171
# DEBUG := 1

# The ID of the GPU that 'make runtest' will use to run unit tests.
TEST_GPUID := 0

# enable pretty build (comment to see full commands)
Q ?= @

```

**Comment by wanghaisheng** [comment]
https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/blob/master/notebooks/OCR/readme.md

➜  OCR docker run -p 8889:8888 -it akshayubhat/dva-auto:caffe-cpu

**Comment by wanghaisheng** [comment]
```
", "")


def process_image(im):
    im, f=resize_im(im, cfg.SCALE, cfg.MAX_SCALE)
    text_lines=text_detector.detect(im)
    for box in text_lines:
        left, top, right, bottom = box[:4]
        img_height, img_width = im.shape[0], im.shape[1]
        padding_x = int((right - left) / 4)
        width = padding_x * 2 + (right - left)
        height = (64 * width / 128)
        padding_y = int((height - (bottom - top))/2)
        new_left = int(max(0, left - padding_x))
        new_right = int(min(img_width - 1, right + padding_x))
        new_top = int(max(0, top - padding_y))
        new_bottom = int(min(img_height - 1, bottom + padding_y))

        plate = im[new_top: new_bottom, new_left: new_right]
        plate = cv2.cvtColor(plate, cv2.COLOR_RGB2GRAY)
        plate = cv2.resize(plate, (128, 64))
        im_gray = plate / 255.
        feed_dict = {x: numpy.stack([im_gray])}
        feed_dict.update(dict(zip(params, param_values)))
        y_val = sess.run(y, feed_dict=feed_dict)

        letter_probs = (y_val[0,
                        0,
                        0, 1:].reshape(
            10, len(common.CHARS)))
        letter_probs = common.softmax(letter_probs)

        present_prob = common.sigmoid(y_val[0, 0, 0, 0])
        predicted_label = letter_probs_to_code(letter_probs)
        if present_prob > 0.5:
            print("predict", predicted_label, present_prob)
            cv2.imshow("plate", plate)
            cv2.putText(im, predicted_label, (left, max(0, int(top - 5))), cv2.FONT_HERSHEY_PLAIN, 2.0, (0, 0, 255), 2)
        cv2.rectangle(im, tuple(box[:2]), tuple(box[2:4]), (0, 255, 0))

return im
```

**Comment by wanghaisheng** [comment]
https://github.com/aovoc/CTPN 
Implement the training process of CTPN. [https://github.com/tianzhi0549/CTPN]

**Comment by wanghaisheng** [comment]
```
# MUST be imported firstly
import sys
import numpy as np

class Config:
    MEAN=np.float32([102.9801, 115.9465, 122.7717])
    TEST_GPU_ID=0
    SCALE=600
    MAX_SCALE=1000

    LINE_MIN_SCORE=0.6
    TEXT_PROPOSALS_MIN_SCORE=0.7
    TEXT_PROPOSALS_NMS_THRESH=0.3
    MAX_HORIZONTAL_GAP=50
    TEXT_LINE_NMS_THRESH=0.3
    MIN_NUM_PROPOSALS=0
    MIN_RATIO=0.9
    MIN_V_OVERLAPS=0.6
    MIN_SIZE_SIM=0.6
    TEXT_PROPOSALS_WIDTH=16

def init():
    sys.path.insert(0, "./tools")
    sys.path.insert(0, "./caffe/python")
    sys.path.insert(0, "./src")
init()



```


```

FROM nvidia/cuda:7.0-runtime-ubuntu14.04
MAINTAINER Varun Suresh <fab.varun@gmail.com>
# docker build -t dc/ctpn .
#docker run  --rm -it -v `pwd`:/opt/ctpn/CTPN/demo_images -p 8888:8888  dc/ctpn /bin/bash
RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        cmake \
        git \
        wget \
        zip \
        unzip \
        libatlas-base-dev \
        libboost-all-dev \
        libgflags-dev \
        libgoogle-glog-dev \
        libhdf5-serial-dev \
        libleveldb-dev \
        liblmdb-dev \
        libopencv-dev \
        libprotobuf-dev \
        libsnappy-dev \
        protobuf-compiler \
        python-dev \
        python-numpy \
        python-pip \
        python-setuptools \
        python-scipy && \
    rm -rf /var/lib/apt/lists/*

ENV CTPN_ROOT=/opt/ctpn
WORKDIR $CTPN_ROOT

RUN git clone https://github.com/wanghaisheng/CTPN
WORKDIR $CTPN_ROOT/CTPN/caffe



ADD ctpn_trained_model.caffemodel  $CTPN_ROOT/CTPN/models



# Missing "packaging" package
RUN pip install -i https://pypi.tuna.tsinghua.edu.cn/simple  --upgrade pip
RUN pip install -i https://pypi.tuna.tsinghua.edu.cn/simple  packaging

RUN cd python && for req in $(cat requirements.txt) pydot; do pip install -i https://pypi.tuna.tsinghua.edu.cn/simple  $req; done && cd ..
RUN git clone https://github.com/NVIDIA/nccl.git
RUN apt-get update && apt-get install -y --no-install-recommends \
    cuda=7.0-28
WORKDIR /

# Download the CUDA drivers from https://developer.nvidia.com/rdp/cudnn-archive and place it here  :
ADD cudnn-7.0-linux-x64-v4.0-prod.tgz /

WORKDIR /cuda
RUN cp -P include/cudnn.h /usr/include
RUN cp -P lib64/libcudnn* /usr/lib/x86_64-linux-gnu/

WORKDIR $CTPN_ROOT/CTPN/caffe

ADD ./caffe/Makefile.config $CTPN_ROOT/CTPN/caffe
RUN cat Makefile.config
#RUN cp Makefile.config.example Makefile.config
RUN apt-get update && apt-get install -y --no-install-recommends \
    vim
#RUN cd nccl && make -j install && 
#RUN    cd .. && rm -rf nccl && \
RUN   cd $CTPN_ROOT/CTPN/caffe  &&   \
   mkdir build && cd build && \
     cmake -DUSE_CUDNN=0 .. && \
#     WITH_PYTHON_LAYER=1 && \
     pwd && \
     make -j"$(nproc)" && make pycaffe

# Set the environment variables so that the paths are correctly configured
ENV PYCAFFE_ROOT $CTPN_ROOT/CTPN/caffe/python
ENV PYTHONPATH $PYCAFFE_ROOT:$PYTHONPATH
ENV PATH $CTPN_ROOT/CTPN/caffe/build/tools:$PYCAFFE_ROOT:$PATH
RUN echo "$CTPN_ROOT/CTPN/caffe/build/lib" >> /etc/ld.so.conf.d/caffe.conf && ldconfig

# To make sure the python layer builds - Need to figure out a cleaner way to do this.
RUN cp $CTPN_ROOT/CTPN/src/layers/* $CTPN_ROOT/CTPN/caffe/src/caffe/layers/
RUN cp $CTPN_ROOT/CTPN/src/*.py $CTPN_ROOT/CTPN/caffe/src/caffe/
RUN cp -r $CTPN_ROOT/CTPN/src/utils $CTPN_ROOT/CTPN/caffe/src/caffe/

# Install Opencv - 2.4.12 :

RUN cd ~ && \
    mkdir -p ocv-tmp && \
    cd ocv-tmp && \
    wget https://github.com/Itseez/opencv/archive/2.4.12.zip  && \
    unzip 2.4.12.zip && \
    cd opencv-2.4.12 && \
    mkdir release && \
    cd release && \
    cmake -D CMAKE_BUILD_TYPE=RELEASE \
          -D CMAKE_INSTALL_PREFIX=/usr/local \
          -D BUILD_PYTHON_SUPPORT=ON \
          .. && \
    make -j8 && \
    make install && \
    rm -rf ~/ocv-tmp


RUN sudo ln /dev/null /dev/raw1394   
WORKDIR $CTPN_ROOT/CTPN
RUN make

RUN mkdir /opt/ctpn/CTPN/output
VOLUME ['/opt/ctpn/CTPN/output/']
RUN pip install --upgrade jupyter 
RUN mkdir -p -m 700 /root/.jupyter/ && \
    echo "c.NotebookApp.ip = '*'" >> /root/.jupyter/jupyter_notebook_config.py

RUN  pip install numpy --upgrade  -i https://pypi.tuna.tsinghua.edu.cn/simple 
RUN  pip install ipyparallel    -i https://pypi.tuna.tsinghua.edu.cn/simple 
WORKDIR /opt/ctpn/CTPN/
EXPOSE 8888

#COPY run_jupyter.sh /

#CMD ["/run_jupyter.sh", "--allow-root"]
#CMD ["jupyter", "notebook", "--no-browser", "--allow-root"]
CMD jupyter notebook --no-browser --ip=0.0.0.0 --allow-root
```

```
import sys
sys.path.append('/opt/ctpn/CTPN/tools/')
from cfg import Config as cfg
#from other import enlarge_boxes, get_output_name, draw_boxes, resize_im, CaffeModel
from other import draw_boxes, resize_im, CaffeModel

import cv2, os, caffe, sys
from detectors import TextProposalDetector, TextDetector
import os.path as osp
from utils.timer import Timer
from IPython.core.display import Image, display
#from tesseract_ocr import tesseract_ocr 


DEMO_IMAGE_DIR="demo_images/pic_folder"
NET_DEF_FILE="models/deploy.prototxt"
MODEL_FILE="models/ctpn_trained_model.caffemodel"

caffe.set_mode_cpu()

#if len(sys.argv)>1 and sys.argv[1]=="--no-gpu":
#    caffe.set_mode_cpu()
#else:
#    caffe.set_mode_gpu()
#    caffe.set_device(cfg.TEST_GPU_ID)

text_proposals_detector=TextProposalDetector(CaffeModel(NET_DEF_FILE, MODEL_FILE))
text_detector=TextDetector(text_proposals_detector)


from glob import glob
timer=Timer()
for im_name in glob("demo_images/pic_folder/*.jpg"):
    print im_name
    im_file=osp.join(im_name)
    im=cv2.imread(im_file)
    timer.tic()
    im, f=resize_im(im, cfg.SCALE, cfg.MAX_SCALE)
    text_lines,text_proposals,scores=text_detector.detect(im)
#    text_lines=enlarge_boxes(text_lines)
    print "Time: %f"%timer.toc()
    print text_lines
   # im_with_text_lines=draw_boxes(im, text_lines, caption=im_name, is_display=True)
    box_count = 0
    for box in text_lines:
        left, top, right, bottom = box[:4]
        img_height, img_width = im.shape[0], im.shape[1]
        padding_x = int((right - left) / 4)
        width = padding_x * 2 + (right - left)
        height = (64 * width / 128)
        padding_y = int((height - (bottom - top))/2)
        new_left = int(max(0, left - padding_x))
        new_right = int(min(img_width - 1, right + padding_x))
        new_top = int(max(0, top - padding_y))
        new_bottom = int(min(img_height - 1, bottom + padding_y))

        crop_img = im[new_top: new_bottom, new_left: new_right]
        #crop_img = cv2.cvtColor(crop_img,cv2.COLOR_RGB2GRAY)
        crop_img = cv2.resize(crop_img, (300,300))
        cv2.imwrite('demo_images/pic_folder/box_text_proposals_{}.jpg'.format(box_count),crop_img)
        box_count += 1     
```

**Comment by wanghaisheng** [comment]
https://github.com/xiaolei89tw/CTPN_XL

**Comment by wanghaisheng** [comment]
https://github.com/bear63/sceneReco

**Comment by wanghaisheng** [comment]
https://github.com/chineseocr/new-text-detection-ctpn

**Comment by wanghaisheng** [comment]
https://github.com/Li-Ming-Fan/OCR-CTPN-CRNN
